language: node_js
node_js:
- '6.0'
install: npm install
deploy:
  provider: s3
  access_key_id: <access_key_id>
  bucket: <bucket_name>
  region: us-west-2
  secret_access_key:
    secure: 1oGDw/HxaPj28bWOioAk6SxKciVTzHmAcHAWOjoiB6rS2HkMS1e787io7NlLIXpIYqwUAZQzeru3ASbZjtI2qzRUWC28Cc6fCp2WhCLlWaQrhD3k8fyNFLJO0X/Wd8PTKaX5tA3JWFR7zjqlr5E2ZbIm+1RfmnnKJi8QFdWz951+spGzNN5vz4gj7+z49fIcwa5xZN4hDnO+x2PVzZbi+Vl7hYw9sv//vxAzu6TkuMvZTUeNOQxTgZCNMxyGuu371Kea7YAfttTsjVRw+3jtP7jF+bTX6N3tuiLHzBNPM8EIr5ykOhLUa1J6RCUVApaJqhgv8DnDRBZwodrAcXM0oqkPQIw3ghccSnE1kUqntpfDHhyYT1rf7d5N186AGUqOJ7YkuM6DbGMWDY0DIE+FMV0RoiUqqX4rxWRo8VfLMbjRT6KS1ZqO+5fTTquojNPD7vkt34rVE3t/6xTgWq3VwEMNgZij5SrtDooCjpsw0p5GWq2bmk6RQ51dwSU0eFxUF8sEXsRzwEtDmALQJbHkS/PXVkKV5Ql17f+C24O7IxHDMo8R1m5EHRshdZE9M9FX9d1yUBo6s+pcGU1z9j+LRXm+/pu6h4IosfacoQ5Hq2BCZolznuzGsyRZlWzdaAV/30A/cxzjcZ1yBoF+iePd4aeSGbkS7R1bBQSjhwdYAOQ=
