language: node_js
node_js:
- '6.0'
before_install: npm install mocha
install: npm install
deploy:
  provider: s3
 # You can refer to environment variables from Travis repo settings!
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
 # Name of the S3 bucket to which your site should be uploaded.
  bucket: fe1.programmingforprogress.com
 # Prevent Travis from deleting your built site so it can be uploaded.
  skip_cleanup: true
  acl: ''
  on:
    repo: pitonisaX/programmingforprogress-frontend
