language: node_js
node_js:
- '6.0'
before_install: npm install mocha
install: npm install
before_deploy: "echo 'ready?'"
deploy:
  provider: s3
 # You can refer to environment variables from Travis repo settings!
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
 # Name of the S3 bucket to which your site should be uploaded.
  #bucket: fe1.programmingforprogress.com
  bucket: fe1.programmingforprogress.com.s3-website-us-west-2.amazonaws.com
 # Prevent Travis from deleting your built site so it can be uploaded.
  skip_cleanup: true
  on:
    repo: pitonisaX/programmingforprogress-frontend
